source "https://rubygems.org"

ruby "~> 3.4.0"

gem "rails", "~> 8.0.0"
gem "pg", "~> 1.5"
gem "puma", ">= 5.0"
gem "faraday", "~> 2.10"
gem "solid_queue"
gem "solid_cache"
gem "solid_cable"
gem "rack-cors"
gem "bcrypt", "~> 3.1"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "rspec-rails", "~> 6.1"
  gem "factory_bot_rails"
end
